// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: transfer.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    to_account_id,
    from_account_id,
    amount
) VALUES (
  $1, $2, $3
)
RETURNING id, to_account_id, from_account_id, amount, created_at
`

type CreateTransferParams struct {
	ToAccountID   int64 `json:"to_account_id"`
	FromAccountID int64 `json:"from_account_id"`
	Amount        int64 `json:"amount"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.ToAccountID, arg.FromAccountID, arg.Amount)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers
WHERE id = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, to_account_id, from_account_id, amount, created_at FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountTransfers = `-- name: ListAccountTransfers :many
SELECT id, to_account_id, from_account_id, amount, created_at FROM transfers
WHERE to_account_id = $3 OR from_account_id = $3
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAccountTransfersParams struct {
	Limit       int64 `json:"limit"`
	Offset      int64 `json:"offset"`
	ToAccountID int64 `json:"to_account_id"`
}

func (q *Queries) ListAccountTransfers(ctx context.Context, arg ListAccountTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listAccountTransfers, arg.Limit, arg.Offset, arg.ToAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ToAccountID,
			&i.FromAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, to_account_id, from_account_id, amount, created_at FROM transfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTransfersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ToAccountID,
			&i.FromAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
